version: '3.9'

services:
  db-postgresql:
    restart: always
    build: ./postgresql
    volumes:
      - ./postgresql/pgdata:/var/lib/postgresql/data/pgdata

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=hssong1024@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=docker123
    ports:
      - 5050:80
    depends_on:
      - db-postgresql

  # app-byGo:
  #   build: ./byGo
