Cloud: {
    Docker-Compose:{
        Fiber(Go): Container{
            Fiber(Go).shape: Text
        }
        Postgresql: Container{
            Postgresql.shape: Text
        }
        Fiber(Go) <-> Postgresql
    }
}

direction: right
Flutter(Dart): Container {
    Flutter(Dart).shape: Text
}
User.shape: person
User <-> Flutter(Dart) <-> Cloud.Docker-Compose.Fiber(Go)
