# 0
FROM golang

WORKDIR /forbuild
COPY . /forbuild/

RUN go install && go build -o appserver -ldflags '-s -w' main.go

# 1
FROM alpine

RUN apk update
RUN apk upgrade
RUN apk add icu-libs gcompat krb5-libs libstdc++ libgcc libc6-compat icu-libs
WORKDIR /
COPY --from=0 /forbuild/appserver /bin/
EXPOSE 3000

CMD ["./bin/appserver"]